export const ORDER_STATUSES = [
  'PENDING',
  'CONFIRMED',
  'PROCESSING',
  'READY',
  'OUT_FOR_DELIVERY',
  'DELIVERED',
  'CANCELLED',
];

export const ORDER_STATUS_FLOW = {
  PENDING: ['CONFIRMED', 'CANCELLED'],
  CONFIRMED: ['PROCESSING', 'CANCELLED'],
  PROCESSING: ['READY', 'CANCELLED'],
  READY: ['OUT_FOR_DELIVERY', 'CANCELLED'],
  OUT_FOR_DELIVERY: ['DELIVERED', 'CANCELLED'],
  DELIVERED: [],
  CANCELLED: [],
};

export const PAYMENT_METHODS = ['CASH', 'UPI', 'PHONEPE', 'SPLIT'];
export const PAYMENT_STATUSES = ['PENDING', 'PAID', 'FAILED', 'NOT_APPLICABLE'];
export const ORDER_TYPES = ['RETAIL', 'WHOLESALE'];
export const ORDER_SOURCES = ['ONLINE', 'IN_STORE'];
export const SPLIT_PAYMENT_METHODS = ['CASH', 'UPI', 'PHONEPE', 'GOOGLE_PAY', 'PAYTM', 'CARD'];

export const INVENTORY_TYPES = [
  'PURCHASE',
  'SALE',
  'MANUAL_ADJUSTMENT',
  'RETURN',
  'CANCELLED_ORDER',
];

export const USER_ROLES = ['customer', 'admin'];
export const CUSTOMER_TYPES = ['RETAIL', 'WHOLESALE'];
